from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, lista_jugadores):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 673)
        MainWindow.setMaximumSize(QtCore.QSize(952, 673))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gif = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/Downloads/ganador-triunfador.gif"))
        self.gif.setScaledContents(True)
        self.gif.setWordWrap(False)
        self.gif.setObjectName("gif")
        self.gridLayout_2.addWidget(self.gif, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.widget_escalera = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_escalera.setObjectName("widget_escalera")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_escalera)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wd_escalon8 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon8.sizePolicy().hasHeightForWidth())
        self.wd_escalon8.setSizePolicy(sizePolicy)
        self.wd_escalon8.setMinimumSize(QtCore.QSize(550, 60))
        self.wd_escalon8.setMaximumSize(QtCore.QSize(550, 70))
        self.wd_escalon8.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon8.setObjectName("wd_escalon8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.wd_escalon8)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ly_escalon8 = QtWidgets.QHBoxLayout()
        self.ly_escalon8.setObjectName("ly_escalon8")
        self.icono_escalon8 = QtWidgets.QLabel(parent=self.wd_escalon8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon8.sizePolicy().hasHeightForWidth())
        self.icono_escalon8.setSizePolicy(sizePolicy)
        self.icono_escalon8.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon8.setText("")
        self.icono_escalon8.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-8-circle-svgrepo-com.png"))
        self.icono_escalon8.setScaledContents(True)
        self.icono_escalon8.setObjectName("icono_escalon8")
        self.ly_escalon8.addWidget(self.icono_escalon8)
        self.tematica_escalon8 = QtWidgets.QLabel(parent=self.wd_escalon8)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon8.setFont(font)
        self.tematica_escalon8.setObjectName("tematica_escalon8")
        self.ly_escalon8.addWidget(self.tematica_escalon8)
        self.horizontalLayout_9.addLayout(self.ly_escalon8)
        self.verticalLayout.addWidget(self.wd_escalon8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon7 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon7.sizePolicy().hasHeightForWidth())
        self.wd_escalon7.setSizePolicy(sizePolicy)
        self.wd_escalon7.setMinimumSize(QtCore.QSize(600, 60))
        self.wd_escalon7.setMaximumSize(QtCore.QSize(600, 70))
        self.wd_escalon7.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon7.setObjectName("wd_escalon7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.wd_escalon7)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ly_escalon7 = QtWidgets.QHBoxLayout()
        self.ly_escalon7.setObjectName("ly_escalon7")
        self.icono_escalon7 = QtWidgets.QLabel(parent=self.wd_escalon7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon7.sizePolicy().hasHeightForWidth())
        self.icono_escalon7.setSizePolicy(sizePolicy)
        self.icono_escalon7.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon7.setText("")
        self.icono_escalon7.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-7-circle-svgrepo-com.png"))
        self.icono_escalon7.setScaledContents(True)
        self.icono_escalon7.setObjectName("icono_escalon7")
        self.ly_escalon7.addWidget(self.icono_escalon7)
        self.tematica_escalon7 = QtWidgets.QLabel(parent=self.wd_escalon7)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon7.setFont(font)
        self.tematica_escalon7.setObjectName("tematica_escalon7")
        self.ly_escalon7.addWidget(self.tematica_escalon7)
        self.horizontalLayout_8.addLayout(self.ly_escalon7)
        self.verticalLayout.addWidget(self.wd_escalon7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon6 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon6.sizePolicy().hasHeightForWidth())
        self.wd_escalon6.setSizePolicy(sizePolicy)
        self.wd_escalon6.setMinimumSize(QtCore.QSize(650, 60))
        self.wd_escalon6.setMaximumSize(QtCore.QSize(650, 70))
        self.wd_escalon6.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon6.setObjectName("wd_escalon6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.wd_escalon6)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ly_escalon6 = QtWidgets.QHBoxLayout()
        self.ly_escalon6.setObjectName("ly_escalon6")
        self.icono_escalon6 = QtWidgets.QLabel(parent=self.wd_escalon6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon6.sizePolicy().hasHeightForWidth())
        self.icono_escalon6.setSizePolicy(sizePolicy)
        self.icono_escalon6.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon6.setText("")
        self.icono_escalon6.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-6-circle-svgrepo-com.png"))
        self.icono_escalon6.setScaledContents(True)
        self.icono_escalon6.setObjectName("icono_escalon6")
        self.ly_escalon6.addWidget(self.icono_escalon6)
        self.tematica_escalon6 = QtWidgets.QLabel(parent=self.wd_escalon6)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon6.setFont(font)
        self.tematica_escalon6.setObjectName("tematica_escalon6")
        self.ly_escalon6.addWidget(self.tematica_escalon6)
        self.horizontalLayout_7.addLayout(self.ly_escalon6)
        self.verticalLayout.addWidget(self.wd_escalon6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon5 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon5.sizePolicy().hasHeightForWidth())
        self.wd_escalon5.setSizePolicy(sizePolicy)
        self.wd_escalon5.setMinimumSize(QtCore.QSize(700, 60))
        self.wd_escalon5.setMaximumSize(QtCore.QSize(700, 70))
        self.wd_escalon5.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon5.setObjectName("wd_escalon5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wd_escalon5)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ly_escalon5 = QtWidgets.QHBoxLayout()
        self.ly_escalon5.setObjectName("ly_escalon5")
        self.icono_escalon5 = QtWidgets.QLabel(parent=self.wd_escalon5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon5.sizePolicy().hasHeightForWidth())
        self.icono_escalon5.setSizePolicy(sizePolicy)
        self.icono_escalon5.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon5.setText("")
        self.icono_escalon5.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-5-circle-svgrepo-com.png"))
        self.icono_escalon5.setScaledContents(True)
        self.icono_escalon5.setObjectName("icono_escalon5")
        self.ly_escalon5.addWidget(self.icono_escalon5)
        self.tematica_escalon5 = QtWidgets.QLabel(parent=self.wd_escalon5)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon5.setFont(font)
        self.tematica_escalon5.setObjectName("tematica_escalon5")
        self.ly_escalon5.addWidget(self.tematica_escalon5)
        self.horizontalLayout_6.addLayout(self.ly_escalon5)
        self.verticalLayout.addWidget(self.wd_escalon5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon4 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon4.sizePolicy().hasHeightForWidth())
        self.wd_escalon4.setSizePolicy(sizePolicy)
        self.wd_escalon4.setMinimumSize(QtCore.QSize(750, 60))
        self.wd_escalon4.setMaximumSize(QtCore.QSize(750, 70))
        self.wd_escalon4.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon4.setObjectName("wd_escalon4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wd_escalon4)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ly_escalon4 = QtWidgets.QHBoxLayout()
        self.ly_escalon4.setObjectName("ly_escalon4")
        self.icono_escalon4 = QtWidgets.QLabel(parent=self.wd_escalon4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon4.sizePolicy().hasHeightForWidth())
        self.icono_escalon4.setSizePolicy(sizePolicy)
        self.icono_escalon4.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon4.setText("")
        self.icono_escalon4.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-4-circle-svgrepo-com.png"))
        self.icono_escalon4.setScaledContents(True)
        self.icono_escalon4.setObjectName("icono_escalon4")
        self.ly_escalon4.addWidget(self.icono_escalon4)
        self.tematica_escalon4 = QtWidgets.QLabel(parent=self.wd_escalon4)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon4.setFont(font)
        self.tematica_escalon4.setObjectName("tematica_escalon4")
        self.ly_escalon4.addWidget(self.tematica_escalon4)
        self.horizontalLayout_5.addLayout(self.ly_escalon4)
        self.verticalLayout.addWidget(self.wd_escalon4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon3 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon3.sizePolicy().hasHeightForWidth())
        self.wd_escalon3.setSizePolicy(sizePolicy)
        self.wd_escalon3.setMinimumSize(QtCore.QSize(800, 60))
        self.wd_escalon3.setMaximumSize(QtCore.QSize(800, 70))
        self.wd_escalon3.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon3.setObjectName("wd_escalon3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wd_escalon3)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ly_escalon3 = QtWidgets.QHBoxLayout()
        self.ly_escalon3.setObjectName("ly_escalon3")
        self.icono_escalon3 = QtWidgets.QLabel(parent=self.wd_escalon3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon3.sizePolicy().hasHeightForWidth())
        self.icono_escalon3.setSizePolicy(sizePolicy)
        self.icono_escalon3.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon3.setText("")
        self.icono_escalon3.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-3-circle-svgrepo-com.png"))
        self.icono_escalon3.setScaledContents(True)
        self.icono_escalon3.setObjectName("icono_escalon3")
        self.ly_escalon3.addWidget(self.icono_escalon3)
        self.tematica_escalon3 = QtWidgets.QLabel(parent=self.wd_escalon3)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon3.setFont(font)
        self.tematica_escalon3.setObjectName("tematica_escalon3")
        self.ly_escalon3.addWidget(self.tematica_escalon3)
        self.horizontalLayout_4.addLayout(self.ly_escalon3)
        self.verticalLayout.addWidget(self.wd_escalon3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon2 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon2.sizePolicy().hasHeightForWidth())
        self.wd_escalon2.setSizePolicy(sizePolicy)
        self.wd_escalon2.setMinimumSize(QtCore.QSize(850, 70))
        self.wd_escalon2.setMaximumSize(QtCore.QSize(850, 70))
        self.wd_escalon2.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon2.setObjectName("wd_escalon2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wd_escalon2)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ly_escalon2 = QtWidgets.QHBoxLayout()
        self.ly_escalon2.setObjectName("ly_escalon2")
        self.icono_escalon2 = QtWidgets.QLabel(parent=self.wd_escalon2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon2.sizePolicy().hasHeightForWidth())
        self.icono_escalon2.setSizePolicy(sizePolicy)
        self.icono_escalon2.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon2.setText("")
        self.icono_escalon2.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-2-circle-svgrepo-com.png"))
        self.icono_escalon2.setScaledContents(True)
        self.icono_escalon2.setObjectName("icono_escalon2")
        self.ly_escalon2.addWidget(self.icono_escalon2)
        self.tematica_escalon2 = QtWidgets.QLabel(parent=self.wd_escalon2)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon2.setFont(font)
        self.tematica_escalon2.setObjectName("tematica_escalon2")
        self.ly_escalon2.addWidget(self.tematica_escalon2)
        self.horizontalLayout_3.addLayout(self.ly_escalon2)
        self.verticalLayout.addWidget(self.wd_escalon2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon1 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon1.sizePolicy().hasHeightForWidth())
        self.wd_escalon1.setSizePolicy(sizePolicy)
        self.wd_escalon1.setMinimumSize(QtCore.QSize(920, 0))
        self.wd_escalon1.setMaximumSize(QtCore.QSize(920, 70))
        self.wd_escalon1.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon1.setObjectName("wd_escalon1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wd_escalon1)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ly_escalon1 = QtWidgets.QHBoxLayout()
        self.ly_escalon1.setObjectName("ly_escalon1")
        self.icono_escalon1 = QtWidgets.QLabel(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon1.sizePolicy().hasHeightForWidth())
        self.icono_escalon1.setSizePolicy(sizePolicy)
        self.icono_escalon1.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon1.setText("")
        self.icono_escalon1.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/number-1-circle-svgrepo-com.png"))
        self.icono_escalon1.setScaledContents(True)
        self.icono_escalon1.setObjectName("icono_escalon1")
        self.ly_escalon1.addWidget(self.icono_escalon1)
        self.tematica_escalon1 = QtWidgets.QLabel(parent=self.wd_escalon1)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon1.setFont(font)
        self.tematica_escalon1.setObjectName("tematica_escalon1")
        self.ly_escalon1.addWidget(self.tematica_escalon1)
        self.wd_j1 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j1.sizePolicy().hasHeightForWidth())
        self.wd_j1.setSizePolicy(sizePolicy)
        self.wd_j1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j1.setStyleSheet("")
        self.wd_j1.setObjectName("wd_j1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.wd_j1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ly_j1 = QtWidgets.QVBoxLayout()
        self.ly_j1.setSpacing(0)
        self.ly_j1.setObjectName("ly_j1")
        self.icon_j1 = QtWidgets.QLabel(parent=self.wd_j1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j1.sizePolicy().hasHeightForWidth())
        self.icon_j1.setSizePolicy(sizePolicy)
        self.icon_j1.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j1.setText("")
        self.icon_j1.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j1.setScaledContents(True)
        self.icon_j1.setObjectName("icon_j1")
        self.ly_j1.addWidget(self.icon_j1)
        self.nombre_j1 = QtWidgets.QLabel(parent=self.wd_j1)
        self.nombre_j1.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j1.setFont(font)
        self.nombre_j1.setObjectName("nombre_j1")
        self.ly_j1.addWidget(self.nombre_j1)
        self.ly_rondas_j1 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j1.setObjectName("ly_rondas_j1")
        self.r1_j1 = QtWidgets.QLabel(parent=self.wd_j1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j1.sizePolicy().hasHeightForWidth())
        self.r1_j1.setSizePolicy(sizePolicy)
        self.r1_j1.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j1.setText("")
        self.r1_j1.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j1.setScaledContents(True)
        self.r1_j1.setObjectName("r1_j1")
        self.ly_rondas_j1.addWidget(self.r1_j1)
        self.r2_j1 = QtWidgets.QLabel(parent=self.wd_j1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j1.sizePolicy().hasHeightForWidth())
        self.r2_j1.setSizePolicy(sizePolicy)
        self.r2_j1.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j1.setText("")
        self.r2_j1.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j1.setScaledContents(True)
        self.r2_j1.setObjectName("r2_j1")
        self.ly_rondas_j1.addWidget(self.r2_j1)
        self.ly_j1.addLayout(self.ly_rondas_j1)
        self.verticalLayout_7.addLayout(self.ly_j1)
        self.ly_escalon1.addWidget(self.wd_j1)
        self.wd_j2 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j2.sizePolicy().hasHeightForWidth())
        self.wd_j2.setSizePolicy(sizePolicy)
        self.wd_j2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j2.setObjectName("wd_j2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.wd_j2)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ly_j2 = QtWidgets.QVBoxLayout()
        self.ly_j2.setSpacing(0)
        self.ly_j2.setObjectName("ly_j2")
        self.icon_j2 = QtWidgets.QLabel(parent=self.wd_j2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j2.sizePolicy().hasHeightForWidth())
        self.icon_j2.setSizePolicy(sizePolicy)
        self.icon_j2.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j2.setText("")
        self.icon_j2.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j2.setScaledContents(True)
        self.icon_j2.setObjectName("icon_j2")
        self.ly_j2.addWidget(self.icon_j2)
        self.nombre_j2 = QtWidgets.QLabel(parent=self.wd_j2)
        self.nombre_j2.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j2.setFont(font)
        self.nombre_j2.setObjectName("nombre_j2")
        self.ly_j2.addWidget(self.nombre_j2)
        self.ly_rondas_j2 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j2.setObjectName("ly_rondas_j2")
        self.r1_j2 = QtWidgets.QLabel(parent=self.wd_j2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j2.sizePolicy().hasHeightForWidth())
        self.r1_j2.setSizePolicy(sizePolicy)
        self.r1_j2.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j2.setText("")
        self.r1_j2.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j2.setScaledContents(True)
        self.r1_j2.setObjectName("r1_j2")
        self.ly_rondas_j2.addWidget(self.r1_j2)
        self.r2_j2 = QtWidgets.QLabel(parent=self.wd_j2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j2.sizePolicy().hasHeightForWidth())
        self.r2_j2.setSizePolicy(sizePolicy)
        self.r2_j2.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j2.setText("")
        self.r2_j2.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j2.setScaledContents(True)
        self.r2_j2.setObjectName("r2_j2")
        self.ly_rondas_j2.addWidget(self.r2_j2)
        self.ly_j2.addLayout(self.ly_rondas_j2)
        self.verticalLayout_8.addLayout(self.ly_j2)
        self.ly_escalon1.addWidget(self.wd_j2)
        self.wd_j3 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j3.sizePolicy().hasHeightForWidth())
        self.wd_j3.setSizePolicy(sizePolicy)
        self.wd_j3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j3.setObjectName("wd_j3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.wd_j3)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ly_j3 = QtWidgets.QVBoxLayout()
        self.ly_j3.setSpacing(0)
        self.ly_j3.setObjectName("ly_j3")
        self.icon_j3 = QtWidgets.QLabel(parent=self.wd_j3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j3.sizePolicy().hasHeightForWidth())
        self.icon_j3.setSizePolicy(sizePolicy)
        self.icon_j3.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j3.setText("")
        self.icon_j3.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j3.setScaledContents(True)
        self.icon_j3.setObjectName("icon_j3")
        self.ly_j3.addWidget(self.icon_j3)
        self.nombre_j3 = QtWidgets.QLabel(parent=self.wd_j3)
        self.nombre_j3.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j3.setFont(font)
        self.nombre_j3.setObjectName("nombre_j3")
        self.ly_j3.addWidget(self.nombre_j3)
        self.ly_rondas_j3 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j3.setObjectName("ly_rondas_j3")
        self.r1_j3 = QtWidgets.QLabel(parent=self.wd_j3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j3.sizePolicy().hasHeightForWidth())
        self.r1_j3.setSizePolicy(sizePolicy)
        self.r1_j3.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j3.setText("")
        self.r1_j3.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j3.setScaledContents(True)
        self.r1_j3.setObjectName("r1_j3")
        self.ly_rondas_j3.addWidget(self.r1_j3)
        self.r2_j3 = QtWidgets.QLabel(parent=self.wd_j3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j3.sizePolicy().hasHeightForWidth())
        self.r2_j3.setSizePolicy(sizePolicy)
        self.r2_j3.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j3.setText("")
        self.r2_j3.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j3.setScaledContents(True)
        self.r2_j3.setObjectName("r2_j3")
        self.ly_rondas_j3.addWidget(self.r2_j3)
        self.ly_j3.addLayout(self.ly_rondas_j3)
        self.verticalLayout_9.addLayout(self.ly_j3)
        self.ly_escalon1.addWidget(self.wd_j3)
        self.wd_j4 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j4.sizePolicy().hasHeightForWidth())
        self.wd_j4.setSizePolicy(sizePolicy)
        self.wd_j4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j4.setObjectName("wd_j4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.wd_j4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ly_j4 = QtWidgets.QVBoxLayout()
        self.ly_j4.setSpacing(0)
        self.ly_j4.setObjectName("ly_j4")
        self.icon_j4 = QtWidgets.QLabel(parent=self.wd_j4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j4.sizePolicy().hasHeightForWidth())
        self.icon_j4.setSizePolicy(sizePolicy)
        self.icon_j4.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j4.setText("")
        self.icon_j4.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j4.setScaledContents(True)
        self.icon_j4.setObjectName("icon_j4")
        self.ly_j4.addWidget(self.icon_j4)
        self.nombre_j4 = QtWidgets.QLabel(parent=self.wd_j4)
        self.nombre_j4.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j4.setFont(font)
        self.nombre_j4.setObjectName("nombre_j4")
        self.ly_j4.addWidget(self.nombre_j4)
        self.ly_rondas_j4 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j4.setObjectName("ly_rondas_j4")
        self.r1_j4 = QtWidgets.QLabel(parent=self.wd_j4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j4.sizePolicy().hasHeightForWidth())
        self.r1_j4.setSizePolicy(sizePolicy)
        self.r1_j4.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j4.setText("")
        self.r1_j4.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j4.setScaledContents(True)
        self.r1_j4.setObjectName("r1_j4")
        self.ly_rondas_j4.addWidget(self.r1_j4)
        self.r2_j4 = QtWidgets.QLabel(parent=self.wd_j4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j4.sizePolicy().hasHeightForWidth())
        self.r2_j4.setSizePolicy(sizePolicy)
        self.r2_j4.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j4.setText("")
        self.r2_j4.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j4.setScaledContents(True)
        self.r2_j4.setObjectName("r2_j4")
        self.ly_rondas_j4.addWidget(self.r2_j4)
        self.ly_j4.addLayout(self.ly_rondas_j4)
        self.verticalLayout_10.addLayout(self.ly_j4)
        self.ly_escalon1.addWidget(self.wd_j4)
        self.wd_j5 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j5.sizePolicy().hasHeightForWidth())
        self.wd_j5.setSizePolicy(sizePolicy)
        self.wd_j5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j5.setObjectName("wd_j5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.wd_j5)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ly_j5 = QtWidgets.QVBoxLayout()
        self.ly_j5.setSpacing(0)
        self.ly_j5.setObjectName("ly_j5")
        self.icon_j5 = QtWidgets.QLabel(parent=self.wd_j5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j5.sizePolicy().hasHeightForWidth())
        self.icon_j5.setSizePolicy(sizePolicy)
        self.icon_j5.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j5.setText("")
        self.icon_j5.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j5.setScaledContents(True)
        self.icon_j5.setObjectName("icon_j5")
        self.ly_j5.addWidget(self.icon_j5)
        self.nombre_j5 = QtWidgets.QLabel(parent=self.wd_j5)
        self.nombre_j5.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j5.setFont(font)
        self.nombre_j5.setObjectName("nombre_j5")
        self.ly_j5.addWidget(self.nombre_j5)
        self.ly_rondas_j5 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j5.setObjectName("ly_rondas_j5")
        self.r1_j5 = QtWidgets.QLabel(parent=self.wd_j5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j5.sizePolicy().hasHeightForWidth())
        self.r1_j5.setSizePolicy(sizePolicy)
        self.r1_j5.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j5.setText("")
        self.r1_j5.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j5.setScaledContents(True)
        self.r1_j5.setObjectName("r1_j5")
        self.ly_rondas_j5.addWidget(self.r1_j5)
        self.r2_j5 = QtWidgets.QLabel(parent=self.wd_j5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j5.sizePolicy().hasHeightForWidth())
        self.r2_j5.setSizePolicy(sizePolicy)
        self.r2_j5.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j5.setText("")
        self.r2_j5.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j5.setScaledContents(True)
        self.r2_j5.setObjectName("r2_j5")
        self.ly_rondas_j5.addWidget(self.r2_j5)
        self.ly_j5.addLayout(self.ly_rondas_j5)
        self.verticalLayout_11.addLayout(self.ly_j5)
        self.ly_escalon1.addWidget(self.wd_j5)
        self.wd_j6 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j6.sizePolicy().hasHeightForWidth())
        self.wd_j6.setSizePolicy(sizePolicy)
        self.wd_j6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j6.setObjectName("wd_j6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.wd_j6)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ly_j6 = QtWidgets.QVBoxLayout()
        self.ly_j6.setSpacing(0)
        self.ly_j6.setObjectName("ly_j6")
        self.icon_j6 = QtWidgets.QLabel(parent=self.wd_j6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j6.sizePolicy().hasHeightForWidth())
        self.icon_j6.setSizePolicy(sizePolicy)
        self.icon_j6.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j6.setText("")
        self.icon_j6.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j6.setScaledContents(True)
        self.icon_j6.setObjectName("icon_j6")
        self.ly_j6.addWidget(self.icon_j6)
        self.nombre_j6 = QtWidgets.QLabel(parent=self.wd_j6)
        self.nombre_j6.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j6.setFont(font)
        self.nombre_j6.setObjectName("nombre_j6")
        self.ly_j6.addWidget(self.nombre_j6)
        self.ly_rondas_j6 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j6.setObjectName("ly_rondas_j6")
        self.r1_j6 = QtWidgets.QLabel(parent=self.wd_j6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j6.sizePolicy().hasHeightForWidth())
        self.r1_j6.setSizePolicy(sizePolicy)
        self.r1_j6.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j6.setText("")
        self.r1_j6.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j6.setScaledContents(True)
        self.r1_j6.setObjectName("r1_j6")
        self.ly_rondas_j6.addWidget(self.r1_j6)
        self.r2_j6 = QtWidgets.QLabel(parent=self.wd_j6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j6.sizePolicy().hasHeightForWidth())
        self.r2_j6.setSizePolicy(sizePolicy)
        self.r2_j6.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j6.setText("")
        self.r2_j6.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j6.setScaledContents(True)
        self.r2_j6.setObjectName("r2_j6")
        self.ly_rondas_j6.addWidget(self.r2_j6)
        self.ly_j6.addLayout(self.ly_rondas_j6)
        self.verticalLayout_13.addLayout(self.ly_j6)
        self.ly_escalon1.addWidget(self.wd_j6)
        self.wd_j7 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j7.sizePolicy().hasHeightForWidth())
        self.wd_j7.setSizePolicy(sizePolicy)
        self.wd_j7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j7.setObjectName("wd_j7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.wd_j7)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.ly_j7 = QtWidgets.QVBoxLayout()
        self.ly_j7.setSpacing(0)
        self.ly_j7.setObjectName("ly_j7")
        self.icon_j7 = QtWidgets.QLabel(parent=self.wd_j7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j7.sizePolicy().hasHeightForWidth())
        self.icon_j7.setSizePolicy(sizePolicy)
        self.icon_j7.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j7.setText("")
        self.icon_j7.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j7.setScaledContents(True)
        self.icon_j7.setObjectName("icon_j7")
        self.ly_j7.addWidget(self.icon_j7)
        self.nombre_j7 = QtWidgets.QLabel(parent=self.wd_j7)
        self.nombre_j7.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j7.setFont(font)
        self.nombre_j7.setObjectName("nombre_j7")
        self.ly_j7.addWidget(self.nombre_j7)
        self.ly_rondas_j7 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j7.setObjectName("ly_rondas_j7")
        self.r1_j7 = QtWidgets.QLabel(parent=self.wd_j7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j7.sizePolicy().hasHeightForWidth())
        self.r1_j7.setSizePolicy(sizePolicy)
        self.r1_j7.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j7.setText("")
        self.r1_j7.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j7.setScaledContents(True)
        self.r1_j7.setObjectName("r1_j7")
        self.ly_rondas_j7.addWidget(self.r1_j7)
        self.r2_j7 = QtWidgets.QLabel(parent=self.wd_j7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j7.sizePolicy().hasHeightForWidth())
        self.r2_j7.setSizePolicy(sizePolicy)
        self.r2_j7.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j7.setText("")
        self.r2_j7.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j7.setScaledContents(True)
        self.r2_j7.setObjectName("r2_j7")
        self.ly_rondas_j7.addWidget(self.r2_j7)
        self.ly_j7.addLayout(self.ly_rondas_j7)
        self.verticalLayout_15.addLayout(self.ly_j7)
        self.ly_escalon1.addWidget(self.wd_j7)
        self.wd_j8 = QtWidgets.QWidget(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_j8.sizePolicy().hasHeightForWidth())
        self.wd_j8.setSizePolicy(sizePolicy)
        self.wd_j8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wd_j8.setObjectName("wd_j8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.wd_j8)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ly_j8 = QtWidgets.QVBoxLayout()
        self.ly_j8.setSpacing(0)
        self.ly_j8.setObjectName("ly_j8")
        self.icon_j8 = QtWidgets.QLabel(parent=self.wd_j8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_j8.sizePolicy().hasHeightForWidth())
        self.icon_j8.setSizePolicy(sizePolicy)
        self.icon_j8.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_j8.setText("")
        self.icon_j8.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/icono_verde.png"))
        self.icon_j8.setScaledContents(True)
        self.icon_j8.setObjectName("icon_j8")
        self.ly_j8.addWidget(self.icon_j8)
        self.nombre_j8 = QtWidgets.QLabel(parent=self.wd_j8)
        self.nombre_j8.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.nombre_j8.setFont(font)
        self.nombre_j8.setObjectName("nombre_j8")
        self.ly_j8.addWidget(self.nombre_j8)
        self.ly_rondas_j8 = QtWidgets.QHBoxLayout()
        self.ly_rondas_j8.setObjectName("ly_rondas_j8")
        self.r1_j8 = QtWidgets.QLabel(parent=self.wd_j8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1_j8.sizePolicy().hasHeightForWidth())
        self.r1_j8.setSizePolicy(sizePolicy)
        self.r1_j8.setMaximumSize(QtCore.QSize(15, 15))
        self.r1_j8.setText("")
        self.r1_j8.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r1_j8.setScaledContents(True)
        self.r1_j8.setObjectName("r1_j8")
        self.ly_rondas_j8.addWidget(self.r1_j8)
        self.r2_j8 = QtWidgets.QLabel(parent=self.wd_j8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2_j8.sizePolicy().hasHeightForWidth())
        self.r2_j8.setSizePolicy(sizePolicy)
        self.r2_j8.setMaximumSize(QtCore.QSize(15, 15))
        self.r2_j8.setText("")
        self.r2_j8.setPixmap(QtGui.QPixmap("../Documents/GitHub/TF_LOS_8_ESCALONES/vista/OneDrive/Escritorio/TF_POO_LOS_8_ESCALONES/vista/img/vacio.png"))
        self.r2_j8.setScaledContents(True)
        self.r2_j8.setObjectName("r2_j8")
        self.ly_rondas_j8.addWidget(self.r2_j8)
        self.ly_j8.addLayout(self.ly_rondas_j8)
        self.verticalLayout_16.addLayout(self.ly_j8)
        self.ly_escalon1.addWidget(self.wd_j8)
        self.horizontalLayout_2.addLayout(self.ly_escalon1)
        self.verticalLayout.addWidget(self.wd_escalon1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_atras = QtWidgets.QPushButton(parent=self.widget_escalera)
        self.pushButton_atras.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_atras.setStyleSheet("color: rgb(0, 0, 0);\n"
        "background-color: rgb(255, 255, 255);\n"
        "")
        self.pushButton_atras.setObjectName("pushButton_atras")
        self.horizontalLayout.addWidget(self.pushButton_atras)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_atras_2 = QtWidgets.QPushButton(parent=self.widget_escalera)
        self.pushButton_atras_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_atras_2.setStyleSheet("color: rgb(0, 0, 0);\n"
        "background-color: rgb(255, 255, 255);\n"
        "")
        self.pushButton_atras_2.setObjectName("pushButton_atras_2")
        self.horizontalLayout.addWidget(self.pushButton_atras_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.widget_escalera, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.__lista_wd = lista_jugadores 

        for i in self.__lista_wd:
            i.setParent(None)
            self.ly_escalon1.addWidget(i)

        self.__lista_layouts = []
        self.__lista_layouts.append(self.ly_escalon1)
        self.__lista_layouts.append(self.ly_escalon2)
        self.__lista_layouts.append(self.ly_escalon3)
        self.__lista_layouts.append(self.ly_escalon4)
        self.__lista_layouts.append(self.ly_escalon5)
        self.__lista_layouts.append(self.ly_escalon6)
        self.__lista_layouts.append(self.ly_escalon7)
        self.__lista_layouts.append(self.ly_escalon8)
        

        self.horizontalLayout_2.addLayout(self.ly_escalon1) #???????????
        self.verticalLayout.addWidget(self.wd_escalon1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout) #???????????
        self.gif = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(750, 10, 191, 81))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("../../Downloads/ganador-triunfador.gif"))
        self.gif.setScaledContents(True)
        self.gif.setWordWrap(False)
        self.gif.setObjectName("gif")
        
        
        self.lista_nombres_escalon = [self.tematica_escalon1, self.tematica_escalon2, self.tematica_escalon3, self.tematica_escalon4, self.tematica_escalon5, self.tematica_escalon6, self.tematica_escalon7, self.tematica_escalon8]

        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton_atras.setProperty("tipo","boton_vista_juego")
        self.pushButton_atras_2.setProperty("tipo","boton_vista_juego")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("VistaJuego", "VistaJuego"))
        self.tematica_escalon8.setText(_translate("MainWindow", "-"))
        self.tematica_escalon7.setText(_translate("MainWindow", "-"))
        self.tematica_escalon6.setText(_translate("MainWindow", "-"))
        self.tematica_escalon5.setText(_translate("MainWindow", "-"))
        self.tematica_escalon4.setText(_translate("MainWindow", "-"))
        self.tematica_escalon3.setText(_translate("MainWindow", "-"))
        self.tematica_escalon2.setText(_translate("MainWindow", "-"))
        self.tematica_escalon1.setText(_translate("MainWindow", "-"))
        self.pushButton_atras_2.setText(_translate("MainWindow","Jugar"))
        self.pushButton_atras.setText(_translate("MainWindow", "Atrás"))


    def get_button_atras(self):
        return self.pushButton_atras

    def get_lista_escalones(self):
        return self.lista_nombres_escalon
    
    def get_lista_layouts(self):
        return self.__lista_layouts
    
    def get_comenzar_partida(self):
        return self.pushButton_atras_2
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

# from PyQt6 import QtCore, QtGui, QtWidgets
# from vista.WidgetJugador import WidgetJugador

# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow, lista_jugadores):
#         MainWindow.setObjectName("MainWindow")
#         #MainWindow.resize(952, 673)
#         #MainWindow.setMaximumSize(QtCore.QSize(952, 673))
#         MainWindow.setFixedSize(1080, 720)

#         #self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
#         self.centralwidget = QtWidgets.QLabel(parent=MainWindow)
#         self.centralwidget.setPixmap(QtGui.QPixmap("vista/img/fondo_escalones.png"))
#         self.centralwidget.setScaledContents(True)
#         self.centralwidget.setObjectName("centralwidget_escalones")
        
#      #    # Layout principal para centrar el widget
#      #     self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
#      #     self.mainLayout.setContentsMargins(0, 0, 0, 0)
#      #     self.mainLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 

#         self.widget_escalera = QtWidgets.QWidget(parent=self.centralwidget)
#         self.widget_escalera.setGeometry(QtCore.QRect(0, 0, 1080, 720))
#         self.widget_escalera.setObjectName("widget_escalera")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_escalera)
#         self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout_2.setSpacing(0)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setSpacing(0)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.wd_escalon8 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         self.wd_escalon8.setSizePolicy(sizePolicy)
#         self.wd_escalon8.setMinimumSize(QtCore.QSize(550, 60))
#         self.wd_escalon8.setMaximumSize(QtCore.QSize(550, 70))
#         self.wd_escalon8.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon8.setObjectName("wd_escalon8")
#         self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.wd_escalon8)
#         self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_9.setObjectName("horizontalLayout_9")
#         self.ly_escalon8 = QtWidgets.QHBoxLayout()
#         self.ly_escalon8.setObjectName("ly_escalon8")
#         self.icono_escalon8 = QtWidgets.QLabel(parent=self.wd_escalon8)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon8.sizePolicy().hasHeightForWidth())
#         self.icono_escalon8.setSizePolicy(sizePolicy)
#         self.icono_escalon8.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon8.setText("")
#         self.icono_escalon8.setPixmap(QtGui.QPixmap("vista/img/number-8-circle-svgrepo-com.png"))
#         self.icono_escalon8.setScaledContents(True)
#         self.icono_escalon8.setObjectName("icono_escalon8")
#         self.ly_escalon8.addWidget(self.icono_escalon8)
#         self.tematica_escalon8 = QtWidgets.QLabel(parent=self.wd_escalon8)
#         font_sitka18 = QtGui.QFont()
#         font_sitka18.setFamily("Sitka")
#         font_sitka18.setPointSize(18)
#         self.tematica_escalon8.setFont(font_sitka18)
#         self.tematica_escalon8.setObjectName("tematica_escalon8")
#         self.ly_escalon8.addWidget(self.tematica_escalon8)
#         self.horizontalLayout_9.addLayout(self.ly_escalon8)
#         self.verticalLayout.addWidget(self.wd_escalon8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon7 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon7.sizePolicy().hasHeightForWidth())
#         self.wd_escalon7.setSizePolicy(sizePolicy)
#         self.wd_escalon7.setMinimumSize(QtCore.QSize(600, 60))
#         self.wd_escalon7.setMaximumSize(QtCore.QSize(600, 70))
#         self.wd_escalon7.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon7.setObjectName("wd_escalon7")
#         self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.wd_escalon7)
#         self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_8.setObjectName("horizontalLayout_8")
#         self.ly_escalon7 = QtWidgets.QHBoxLayout()
#         self.ly_escalon7.setObjectName("ly_escalon7")
#         self.icono_escalon7 = QtWidgets.QLabel(parent=self.wd_escalon7)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon7.sizePolicy().hasHeightForWidth())
#         self.icono_escalon7.setSizePolicy(sizePolicy)
#         self.icono_escalon7.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon7.setText("")
#         self.icono_escalon7.setPixmap(QtGui.QPixmap("vista/img/number-7-circle-svgrepo-com.png"))
#         self.icono_escalon7.setScaledContents(True)
#         self.icono_escalon7.setObjectName("icono_escalon7")
#         self.ly_escalon7.addWidget(self.icono_escalon7)
#         self.tematica_escalon7 = QtWidgets.QLabel(parent=self.wd_escalon7)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon7.setFont(font)
#         self.tematica_escalon7.setObjectName("tematica_escalon7")
#         self.ly_escalon7.addWidget(self.tematica_escalon7)
#         self.horizontalLayout_8.addLayout(self.ly_escalon7)
#         self.verticalLayout.addWidget(self.wd_escalon7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon6 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon6.sizePolicy().hasHeightForWidth())
#         self.wd_escalon6.setSizePolicy(sizePolicy)
#         self.wd_escalon6.setMinimumSize(QtCore.QSize(650, 60))
#         self.wd_escalon6.setMaximumSize(QtCore.QSize(650, 70))
#         self.wd_escalon6.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon6.setObjectName("wd_escalon6")
#         self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.wd_escalon6)
#         self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_7.setObjectName("horizontalLayout_7")
#         self.ly_escalon6 = QtWidgets.QHBoxLayout()
#         self.ly_escalon6.setObjectName("ly_escalon6")
#         self.icono_escalon6 = QtWidgets.QLabel(parent=self.wd_escalon6)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon6.sizePolicy().hasHeightForWidth())
#         self.icono_escalon6.setSizePolicy(sizePolicy)
#         self.icono_escalon6.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon6.setText("")
#         self.icono_escalon6.setPixmap(QtGui.QPixmap("vista/img/number-6-circle-svgrepo-com.png"))
#         self.icono_escalon6.setScaledContents(True)
#         self.icono_escalon6.setObjectName("icono_escalon6")
#         self.ly_escalon6.addWidget(self.icono_escalon6)
#         self.tematica_escalon6 = QtWidgets.QLabel(parent=self.wd_escalon6)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon6.setFont(font)
#         self.tematica_escalon6.setObjectName("tematica_escalon6")
#         self.ly_escalon6.addWidget(self.tematica_escalon6)
#         self.horizontalLayout_7.addLayout(self.ly_escalon6)
#         self.verticalLayout.addWidget(self.wd_escalon6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon5 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon5.sizePolicy().hasHeightForWidth())
#         self.wd_escalon5.setSizePolicy(sizePolicy)
#         self.wd_escalon5.setMinimumSize(QtCore.QSize(700, 60))
#         self.wd_escalon5.setMaximumSize(QtCore.QSize(700, 70))
#         self.wd_escalon5.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon5.setObjectName("wd_escalon5")
#         self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wd_escalon5)
#         self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_6.setObjectName("horizontalLayout_6")
#         self.ly_escalon5 = QtWidgets.QHBoxLayout()
#         self.ly_escalon5.setObjectName("ly_escalon5")
#         self.icono_escalon5 = QtWidgets.QLabel(parent=self.wd_escalon5)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon5.sizePolicy().hasHeightForWidth())
#         self.icono_escalon5.setSizePolicy(sizePolicy)
#         self.icono_escalon5.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon5.setText("")
#         self.icono_escalon5.setPixmap(QtGui.QPixmap("vista/img/number-5-circle-svgrepo-com.png"))
#         self.icono_escalon5.setScaledContents(True)
#         self.icono_escalon5.setObjectName("icono_escalon5")
#         self.ly_escalon5.addWidget(self.icono_escalon5)
#         self.tematica_escalon5 = QtWidgets.QLabel(parent=self.wd_escalon5)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon5.setFont(font)
#         self.tematica_escalon5.setObjectName("tematica_escalon5")
#         self.ly_escalon5.addWidget(self.tematica_escalon5)
#         self.horizontalLayout_6.addLayout(self.ly_escalon5)
#         self.verticalLayout.addWidget(self.wd_escalon5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon4 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon4.sizePolicy().hasHeightForWidth())
#         self.wd_escalon4.setSizePolicy(sizePolicy)
#         self.wd_escalon4.setMinimumSize(QtCore.QSize(750, 60))
#         self.wd_escalon4.setMaximumSize(QtCore.QSize(750, 70))
#         self.wd_escalon4.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon4.setObjectName("wd_escalon4")
#         self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wd_escalon4)
#         self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_5.setObjectName("horizontalLayout_5")
#         self.ly_escalon4 = QtWidgets.QHBoxLayout()
#         self.ly_escalon4.setObjectName("ly_escalon4")
#         self.icono_escalon4 = QtWidgets.QLabel(parent=self.wd_escalon4)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon4.sizePolicy().hasHeightForWidth())
#         self.icono_escalon4.setSizePolicy(sizePolicy)
#         self.icono_escalon4.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon4.setText("")
#         self.icono_escalon4.setPixmap(QtGui.QPixmap("vista/img/number-4-circle-svgrepo-com.png"))
#         self.icono_escalon4.setScaledContents(True)
#         self.icono_escalon4.setObjectName("icono_escalon4")
#         self.ly_escalon4.addWidget(self.icono_escalon4)
#         self.tematica_escalon4 = QtWidgets.QLabel(parent=self.wd_escalon4)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon4.setFont(font)
#         self.tematica_escalon4.setObjectName("tematica_escalon4")
#         self.ly_escalon4.addWidget(self.tematica_escalon4)
#         self.horizontalLayout_5.addLayout(self.ly_escalon4)
#         self.verticalLayout.addWidget(self.wd_escalon4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon3 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon3.sizePolicy().hasHeightForWidth())
#         self.wd_escalon3.setSizePolicy(sizePolicy)
#         self.wd_escalon3.setMinimumSize(QtCore.QSize(800, 60))
#         self.wd_escalon3.setMaximumSize(QtCore.QSize(800, 70))
#         self.wd_escalon3.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon3.setObjectName("wd_escalon3")
#         self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wd_escalon3)
#         self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_4.setObjectName("horizontalLayout_4")
#         self.ly_escalon3 = QtWidgets.QHBoxLayout()
#         self.ly_escalon3.setObjectName("ly_escalon3")
#         self.icono_escalon3 = QtWidgets.QLabel(parent=self.wd_escalon3)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon3.sizePolicy().hasHeightForWidth())
#         self.icono_escalon3.setSizePolicy(sizePolicy)
#         self.icono_escalon3.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon3.setText("")
#         self.icono_escalon3.setPixmap(QtGui.QPixmap("vista/img/number-3-circle-svgrepo-com.png"))
#         self.icono_escalon3.setScaledContents(True)
#         self.icono_escalon3.setObjectName("icono_escalon3")
#         self.ly_escalon3.addWidget(self.icono_escalon3)
#         self.tematica_escalon3 = QtWidgets.QLabel(parent=self.wd_escalon3)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon3.setFont(font)
#         self.tematica_escalon3.setObjectName("tematica_escalon3")
#         self.ly_escalon3.addWidget(self.tematica_escalon3)
#         self.horizontalLayout_4.addLayout(self.ly_escalon3)
#         self.verticalLayout.addWidget(self.wd_escalon3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon2 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon2.sizePolicy().hasHeightForWidth())
#         self.wd_escalon2.setSizePolicy(sizePolicy)
#         self.wd_escalon2.setMinimumSize(QtCore.QSize(850, 70))
#         self.wd_escalon2.setMaximumSize(QtCore.QSize(850, 70))
#         self.wd_escalon2.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon2.setObjectName("wd_escalon2")
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wd_escalon2)
#         self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_3.setObjectName("horizontalLayout_3")
#         self.ly_escalon2 = QtWidgets.QHBoxLayout()
#         self.ly_escalon2.setObjectName("ly_escalon2")
#         self.icono_escalon2 = QtWidgets.QLabel(parent=self.wd_escalon2)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon2.sizePolicy().hasHeightForWidth())
#         self.icono_escalon2.setSizePolicy(sizePolicy)
#         self.icono_escalon2.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon2.setText("")
#         self.icono_escalon2.setPixmap(QtGui.QPixmap("vista/img/number-2-circle-svgrepo-com.png"))
#         self.icono_escalon2.setScaledContents(True)
#         self.icono_escalon2.setObjectName("icono_escalon2")
#         self.ly_escalon2.addWidget(self.icono_escalon2)
#         self.tematica_escalon2 = QtWidgets.QLabel(parent=self.wd_escalon2)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon2.setFont(font)
#         self.tematica_escalon2.setObjectName("tematica_escalon2")
#         self.ly_escalon2.addWidget(self.tematica_escalon2)
#         self.horizontalLayout_3.addLayout(self.ly_escalon2)
#         self.verticalLayout.addWidget(self.wd_escalon2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.wd_escalon1 = QtWidgets.QWidget(parent=self.widget_escalera)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.wd_escalon1.sizePolicy().hasHeightForWidth())
#         self.wd_escalon1.setSizePolicy(sizePolicy)
#         self.wd_escalon1.setMinimumSize(QtCore.QSize(920, 0))
#         self.wd_escalon1.setMaximumSize(QtCore.QSize(920, 70))
#         #self.wd_escalon1.setStyleSheet("background-color: rgb(213, 213, 213);")
#         self.wd_escalon1.setObjectName("wd_escalon1")
#         self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wd_escalon1)
#         self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
#         self.horizontalLayout_2.setObjectName("horizontalLayout_2")
#         self.ly_escalon1 = QtWidgets.QHBoxLayout()
#         self.ly_escalon1.setObjectName("ly_escalon1")
#         self.icono_escalon1 = QtWidgets.QLabel(parent=self.wd_escalon1)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.icono_escalon1.sizePolicy().hasHeightForWidth())
#         self.icono_escalon1.setSizePolicy(sizePolicy)
#         self.icono_escalon1.setMaximumSize(QtCore.QSize(50, 50))
#         self.icono_escalon1.setText("")
#         self.icono_escalon1.setPixmap(QtGui.QPixmap("vista/img/number-1-circle-svgrepo-com.png"))
#         self.icono_escalon1.setScaledContents(True)
#         self.icono_escalon1.setObjectName("icono_escalon1")
#         self.ly_escalon1.addWidget(self.icono_escalon1)
#         self.tematica_escalon1 = QtWidgets.QLabel(parent=self.wd_escalon1)
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(18)
#         self.tematica_escalon1.setFont(font)
#         self.tematica_escalon1.setObjectName("tematica_escalon1")
#         self.ly_escalon1.addWidget(self.tematica_escalon1)

#         self.__lista_wd = lista_jugadores 

#         for i in self.__lista_wd:
#             i.setParent(None)
#             self.ly_escalon1.addWidget(i)

#         self.__lista_layouts = []
#         self.__lista_layouts.append(self.ly_escalon1)
#         self.__lista_layouts.append(self.ly_escalon2)
#         self.__lista_layouts.append(self.ly_escalon3)
#         self.__lista_layouts.append(self.ly_escalon4)
#         self.__lista_layouts.append(self.ly_escalon5)
#         self.__lista_layouts.append(self.ly_escalon6)
#         self.__lista_layouts.append(self.ly_escalon7)
#         self.__lista_layouts.append(self.ly_escalon8)
        

#         self.horizontalLayout_2.addLayout(self.ly_escalon1) #???????????
#         self.verticalLayout.addWidget(self.wd_escalon1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
#         self.verticalLayout_2.addLayout(self.verticalLayout) #???????????
#         self.gif = QtWidgets.QLabel(parent=self.centralwidget)
#         self.gif.setGeometry(QtCore.QRect(750, 10, 191, 81))
#         self.gif.setText("")
#         self.gif.setPixmap(QtGui.QPixmap("../../Downloads/ganador-triunfador.gif"))
#         self.gif.setScaledContents(True)
#         self.gif.setWordWrap(False)
#         self.gif.setObjectName("gif")
#         self.pushButton_atras = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton_atras.setGeometry(QtCore.QRect(30, 660, 75, 30))
#         self.pushButton_atras.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        
#         self.pushButton_comenzar_partida = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton_comenzar_partida.setGeometry(QtCore.QRect(980, 660, 75, 30))
#         self.pushButton_comenzar_partida.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        
#         self.lista_nombres_escalon = [self.tematica_escalon1, self.tematica_escalon2, self.tematica_escalon3, self.tematica_escalon4, self.tematica_escalon5, self.tematica_escalon6, self.tematica_escalon7, self.tematica_escalon8]

#         MainWindow.setCentralWidget(self.centralwidget)

#         self.pushButton_atras.setProperty("tipo","boton_vista_juego")
#         self.pushButton_comenzar_partida.setProperty("tipo","boton_vista_juego")

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("VistaJuego", "VistaJuego"))
#         self.tematica_escalon8.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon7.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon6.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon5.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon4.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon3.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon2.setText(_translate("MainWindow", "-"))
#         self.tematica_escalon1.setText(_translate("MainWindow", "-"))
#         self.pushButton_comenzar_partida.setText(_translate("MainWindow","Jugar"))
#         self.pushButton_atras.setText(_translate("MainWindow", "Atrás"))


#     def get_button_atras(self):
#         return self.pushButton_atras

#     def get_lista_escalones(self):
#         return self.lista_nombres_escalon
    
#     def get_lista_layouts(self):
#         return self.__lista_layouts
    
#     def get_comenzar_partida(self):
#         return self.pushButton_comenzar_partida
    
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)

#     # Suponiendo que tienes una lista de jugadores
#     lista_jugadores = [
#         {"nombre": "Jugador 1", "imagen": "ruta_imagen1.png"},
#         {"nombre": "Jugador 2", "imagen": "ruta_imagen2.png"},
#         # Agrega más jugadores aquí
#     ]

#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow, lista_jugadores)
#     MainWindow.show()

#     sys.exit(app.exec())
