
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(1080, 720)
        MainWindow.setWindowIcon(QtGui.QIcon('vista/img/configuracion_icono.png'))
        #self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget = QtWidgets.QLabel(parent=MainWindow)
        self.centralwidget.setPixmap(QtGui.QPixmap("vista/img/fondo_escalones.png"))
        self.centralwidget.setScaledContents(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setPixmap(QtGui.QPixmap("vista/img/temas_titulo.png"))
        self.label.setScaledContents(True)
        self.label.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#ffffff; font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.QLine_Buscar = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QLine_Buscar.setFont(font)
        self.QLine_Buscar.setObjectName("QLine_Buscar")
        self.horizontalLayout_2.addWidget(self.QLine_Buscar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.QTable_Temas = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QTable_Temas.setFont(font)
        self.QTable_Temas.setRowCount(0)
        self.QTable_Temas.setColumnCount(0)
        self.QTable_Temas.setObjectName("QTable_Temas")
        self.verticalLayout.addWidget(self.QTable_Temas)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Volver = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Volver.setFont(font)
        self.pushButton_Volver.setObjectName("pushButton_Volver")
        self.horizontalLayout_3.addWidget(self.pushButton_Volver)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_Nuevo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Nuevo.setIcon(QtGui.QIcon("vista/img/icono_agregar.png"))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Nuevo.setFont(font)
        self.pushButton_Nuevo.setObjectName("pushButton_Nuevo")
        self.horizontalLayout_3.addWidget(self.pushButton_Nuevo)
        self.pushButton_Modificar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Modificar.setIcon(QtGui.QIcon("vista/img/icono_modificar.png"))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Modificar.setFont(font)
        self.pushButton_Modificar.setObjectName("pushButton_Modificar")
        self.horizontalLayout_3.addWidget(self.pushButton_Modificar)
        self.pushButton_Eliminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Eliminar.setIcon(QtGui.QIcon("vista/img/icono_eliminar.png"))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Eliminar.setFont(font)
        self.pushButton_Eliminar.setObjectName("pushButton_Eliminar")
        self.horizontalLayout_3.addWidget(self.pushButton_Eliminar)


        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_Eliminar.setProperty("tipo","boton_vista_configuracion_eliminar")
        self.pushButton_Modificar.setProperty("tipo","boton_vista_configuracion")
        self.pushButton_Nuevo.setProperty("tipo","boton_vista_configuracion_agregar")
        self.pushButton_Volver.setProperty("tipo","boton_vista_configuracion")

    def aviso_seleccionar_tema(self):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
        msg.setWindowTitle("Advertencia")
        msg.setText("Debe seleccionar un tema para modificar")
        msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        msg.exec()
        

    def aviso_seleccion_tema(self):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
        msg.setWindowTitle("Advertencia")
        msg.setText("Debe seleccionar un tema para eliminar")
        msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        msg.exec()

    def informamos_tema_modificado(self,tema):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
        msg.setWindowTitle("Modificacion Existosa")
        msg.setText(f"Se Modifico correctamente el tema: {tema}")
        msg.exec()

    def aviso_eliminar_tema(self,tema):
        mensaje = QtWidgets.QMessageBox()
        mensaje.setIcon(QtWidgets.QMessageBox.Icon.Warning)
        mensaje.setWindowTitle("Eliminar Tema")
        mensaje.setText(f"¿Estás seguro de que deseas eliminar el tema '{tema.get_nombreTema()}'?")
        mensaje.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No)
        respuesta=mensaje.exec()
        return respuesta

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("VistaConfiguracionTemaABM", "Configuración de Temas"))
        #self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Temas</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Buscar:  "))
        self.pushButton_Nuevo.setText(_translate("MainWindow", " Nuevo"))
        self.pushButton_Modificar.setText(_translate("MainWindow", " Modificar"))
        self.pushButton_Eliminar.setText(_translate("MainWindow", " Eliminar"))
        self.pushButton_Volver.setText(_translate("MainWindow", " Volver "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
